# Generated by Django 5.2 on 2025-04-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('disponivel', models.BooleanField(verbose_name='Disponivel')),
            ],
        ),
    ]
