# Generated by Django 5.2 on 2025-04-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_produto_descricao_alter_produto_disponivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, max_length=55, verbose_name='Descrição'),
        ),
    ]
